name: stream_sample
description: An absolute bare-bones web app.
version: 0.0.1
#homepage: https://www.example.com
#author: patorash <email@example.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

#dependencies:
#  path: ^1.4.1

dependencies:
  stream: any
  angular: ^4.0.0
  angular_forms: ^1.0.0
  angular_router: ^1.0.2

dev_dependencies:
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1
  grinder: "^0.8.0+3"
  watcher: "^0.9.7+4"
  sass: "^1.0.0-alpha"
  dart_sass_transformer: "^0.5.0+1"

transformers:
- angular:
    entry_points:
    - web/client/js/main.dart
- dart_to_js_script_rewriter
- dart_sass_transformer:
    executable: sassc

# Uncomment the following in sdk 1.24+ to make pub serve
# use dartdevc (webdev.dartlang.org/tools/dartdevc).
# web:
#  compiler:
#    debug: dartdevc
